ShawnaThai Eiei/Controllers/ForgotPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using ShawnaThai_Eiei.Models;

namespace ShawnaThai_Eiei.Controllers
{

    public class ForgotPasswordController : Controller
    {
        ShawnaThaiEntities db = new ShawnaThaiEntities();
        // GET: ForgotPassword
        [HttpGet]


        public ActionResult SelectForgot()
        {
            return View();
        }

        public ActionResult ForgotAdminID()
        {
            string AD_Email = Request.Form["AD_Email"];
            string AD_ID = Request.Form["AD_ID"];
            string AD_Tel = Request.Form["AD_Tel"];
            var check = db.Admin_Cooperative.Where(b => b.AD_ID.Equals(AD_ID)).FirstOrDefault<Admin_Cooperative>();
            var check2 = db.Admin_Cooperative.Where(b => b.AD_Tel.Equals(AD_Tel)).FirstOrDefault<Admin_Cooperative>();
            if (check != null && check2 != null)
            {
                var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
                var stringChars = new char[8];
                var random = new Random();

                for (int i = 0; i < stringChars.Length; i++)
                {
                    stringChars[i] = chars[random.Next(chars.Length)];
                }

                var finalString = new String(stringChars);
                check.AD_Password = finalString;
                db.SaveChanges();
                using (MailMessage mma = new MailMessage("shawnathaidpu@gmail.com", AD_Email))
                {
                    mma.Subject = "Reset Password";

                    mma.Body = "รหัสผ่านใหม่ของคุณคือ : " + check.AD_Password;


                    mma.IsBodyHtml = false;
                    using (SmtpClient smtp = new SmtpClient())
                    {
                        smtp.Host = "smtp.gmail.com";
                        smtp.Port = 587;
                        smtp.EnableSsl = true;
                        NetworkCredential NetworkCred = new NetworkCredential("shawnathaidpu@gmail.com", "Gear2404");
                        smtp.UseDefaultCredentials = true;
                        smtp.Credentials = NetworkCred;
                        smtp.Send(mma);
                        ViewBag.ok = "OK";
                    }
                }
            }

            return View();

        }

        public ActionResult ForgotUserID()
        {
            string Users_Email = Request.Form["User_Email"];
            string IDCard = Request.Form["IDCard"];
            string User_Tel = Request.Form["User_Tel"];
            var check = db.Users.Where(b => b.U_IDCard.Equals(IDCard)).FirstOrDefault<User>();
            var check2 = db.Users.Where(b => b.U_Tel.Equals(User_Tel)).FirstOrDefault<User>();
            if (check != null && check2 != null)
            {
                var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
                var stringChars = new char[8];
                var random = new Random();

                for (int i = 0; i < stringChars.Length; i++)
                {
                    stringChars[i] = chars[random.Next(chars.Length)];
                }

                var finalString = new String(stringChars);
                check.U_Password = finalString;
                db.SaveChanges();
                using (MailMessage mm = new MailMessage("shawnathaidpu@gmail.com", Users_Email))
                {
                    mm.Subject = "Reset Password";

                    mm.Body = "รหัสผ่านใหม่ของคุณคือ : " + check.U_Password;


                    mm.IsBodyHtml = false;
                    using (SmtpClient smtp = new SmtpClient())
                    {
                        smtp.Host = "smtp.gmail.com";
                        smtp.Port = 587;
                        smtp.EnableSsl = true;
                        NetworkCredential NetworkCred = new NetworkCredential("shawnathaidpu@gmail.com", "Gear2404");
                        smtp.UseDefaultCredentials = true;
                        smtp.Credentials = NetworkCred;
                        smtp.Send(mm);
                        ViewBag.ok = "OK";
                    }
                }

            }

            return View();

        }
    }
}

ShawnaThai Eiei/Views/ForgotPassword/ForgotAdminID.cshtml
@{
    ViewBag.Title = "ForgotAdminID";
}

<html>
<head>
    <style type="text/css">
        .masthead {
            height: 980px
        }
    </style>
</head>

@using (Html.BeginForm())
{
    <body id="page-top">
        <header class="masthead">
            <div class="container">
                <div class="intro-text">
                    <div class="intro-heading" style="font-size:50px;position:relative;top:-160px;">กรอกข้อมูลเพื่อ รีเซ็ตรหัสผ่าน</div>
                    <div class="col-md-12">
                        <br><br><br><br>

                        <div class="form-group">
                            <div class="col-md-4" style="text-align:left; position:relative;right:-370px;top:-200px;">
                                <label style="color:white;font-size:24px;">อีเมล์ : </label>
                            </div>
                            <div class="col-md-8" style="text-align:left; position:relative;right:-450px; top:-240px">
                                <input id="AD_Email" name="AD_Email" class="form-control" style="width:300px" type="text" maxlength="50" title="ใส่อีเมล์ที่ต้องการจะส่ง">
                                <br />
                            </div>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4" style="text-align:left; position:relative;right:-305px;top:-220px;">
                                <label style="color:white;font-size:24px;">แอดมินไอดี : </label>
                            </div>
                            <div class="col-md-8" style="text-align:left; position:relative;right:-450px; top:-260px">
                                <input id="AD_ID" name="AD_ID" class="form-control" style="width:300px" pattern="[a-zA-Z0-9]+" type="text" minlength="6" maxlength="18" title="ใส่รหัสแอดมินของท่าน">
                                <p style="color:red ; font-weight:bold">@ViewBag.Error1</p>
                                <br />
                            </div>
                            <p class="help-block text-danger"></p>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="text-align:left; position:relative;right:-285px;top:-250px;">
                                <label style="color:white;font-size:24px;">เบอร์โทรศัพท์ : </label>
                            </div>
                            <div class="col-md-8" style="text-align:left; position:relative;right:-450px; top:-290px">
                                <input id="AD_Tel" name="AD_Tel" class="form-control" style="width:300px" pattern="[0-9]+" type="text" maxlength="10" title="ใส่เบอร์โทรศัพท์">
                                <p style="color:red ; font-weight:bold">@ViewBag.Error2</p>
                                <br />
                            </div>
                            <p class="help-block text-danger"></p>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8" style="position:relative;right:-200px;top:-280px;">
                                <input class="btn btn-xl" type="submit" value="รีเซ็ตรหัสผ่าน" onclick="myFunction()" />
                                <input class="btn btn-xl" type="submit" value="ย้อนกลับ" onclick="location.href='@Url.Action("SelectForgot", "ForgotPassword")';" />
                            </div>
                        </div>

                        @if (ViewBag.ok != null)
                        {

                            <script>
                                    alert("รหัสผ่านใหม่จะถูกส่งไปยังอีเมล์ของท่าน");
                            </script>

                        }
                    </div>
                </div>
                <hr />
            </div>
        </header>
    </body>
}
</html>

ShawnaThai Eiei/Views/ForgotPassword/ForgotUserID.cshtml
@{
    ViewBag.Title = "ForgotUserID";
}

<html>
<head>
    <style type="text/css">
        .masthead {
            height: 980px
        }
    </style>
</head>

@using (Html.BeginForm())
{
    <body id="page-top">
        <header class="masthead">
            <div class="container">
                <div class="intro-text">
                    <div class="intro-heading" style="font-size:50px;position:relative;top:-160px;">กรอกข้อมูลเพื่อ รีเซ็ตรหัสผ่าน</div>
                    <div class="col-md-12">
                        <br><br><br><br>

                        <div class="form-group">
                            <div class="col-md-4" style="text-align:left; position:relative;right:-370px;top:-200px;">
                                <label style="color:white;font-size:24px;">อีเมล์ : </label>
                            </div>
                            <div class="col-md-8" style="text-align:left; position:relative;right:-450px; top:-240px">
                                <input id="User_Email" name="User_Email" class="form-control" style="width:300px" type="text" maxlength="50" title="ใส่อีเมล์ที่ต้องการจะส่ง">
                                <br />
                            </div>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4" style="text-align:left; position:relative;right:-250px;top:-220px;">
                                <label style="color:white;font-size:24px;">เลขบัตรประชาชน : </label>
                            </div>
                            <div class="col-md-8" style="text-align:left; position:relative;right:-450px; top:-260px">
                                <input id="IDCard" name="IDCard" class="form-control" style="width:300px" pattern="[0-9]+" type="text" minlength="13" maxlength="13" title="ใส่เลขบัตรประชาชน">
                                <p style="color:red ; font-weight:bold">@ViewBag.Error1</p>
                                <br />
                            </div>
                            <p class="help-block text-danger"></p>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="text-align:left; position:relative;right:-285px;top:-250px;">
                                <label style="color:white;font-size:24px;">เบอร์โทรศัพท์ : </label>
                            </div>
                            <div class="col-md-8" style="text-align:left; position:relative;right:-450px; top:-290px">
                                <input id="User_Tel" name="User_Tel" class="form-control" style="width:300px" pattern="[0-9]+" type="text" maxlength="10" title="ใส่เบอร์โทรศัพท์">
                                <p style="color:red ; font-weight:bold">@ViewBag.Error2</p>
                                <br />
                            </div>
                            <p class="help-block text-danger"></p>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8" style="position:relative;right:-200px;top:-280px;">
                                <input class="btn btn-xl" type="submit" value="รีเซ็ตรหัสผ่าน" onclick="myFunction()" />
                                <input class="btn btn-xl" type="submit" value="ย้อนกลับ" onclick="location.href='@Url.Action("SelectForgot","ForgotPassword")';" />
                            </div>
                        </div>
                        @if (ViewBag.ok != null)
                        {

                            <script>
                                alert("รหัสผ่านใหม่จะถูกส่งไปยังอีเมล์ของท่าน");
                            </script>

                        }
                    </div>
                </div>
                <hr />
            </div>
        </header>
    </body>
}
</html>

ShawnaThai Eiei/Views/ForgotPassword/SelectForgot.cshtml
@{
    ViewBag.Title = "SelectForgot";
}

<html lang="en">
<head>
    <style type="text/css">
        .masthead {
            height: 980px
        }
    </style>
</head>

<body id="page-top">
    <header class="masthead">
        <div class="container">
            <div class="intro-text">
                <div class="intro-heading" style="font-size:50px;position:relative;top:-160px;">เลือกระดับผู้ใช้ของคุณ เพื่อรีเซ็ตรหัสผ่าน</div>
                <div class="col-md-12">
                    <br><br><br><br>
                    <div class="form-group">
                        <img src="~/Icon/icons-390z.png" style="position:relative;top:-200px;right:50px;" onclick="location.href='@Url.Action("ForgotUserID", "ForgotPassword")';">
                        <img src="~/Icon/icons-390.png" style="position:relative;top:-200px;right:-50px;" onclick="location.href='@Url.Action("ForgotAdminID", "ForgotPassword")';">
                        <div class="col-md-4" style="text-align:left; position:relative;right:-268px;top:-180px">
                            <label style="color:gold;font-size:70px;">ผู้ใช้</label>
                        </div>
                        <div class="col-md-4" style="text-align:left; position:relative;right:-630px; top:-295px">
                            <label style="color:gold;font-size:70px;">แอดมิน</label>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
        </div>
    </header>
</body>
</html>